--------------------------------------------------------
--  File created - Wednesday-April-27-2016   
--------------------------------------------------------
@C:\Users\Samiksha\BIN_X_yecELgSGabUHGShSs_lA==_0.sql
@C:\Users\Samiksha\BIN_dWNUZEuJQS24wJpLIHRMFA==_0.sql
@C:\Users\Samiksha\BIN_jTib5X59TCitUh6p6Zjylw==_0.sql
@C:\Users\Samiksha\COMPANY.sql
@C:\Users\Samiksha\PLACEMENT.sql
@C:\Users\Samiksha\STUDENT.sql
--@C:\Users\Samiksha\BIN_X_yecELgSGabUHGShSs_lA==_0_DATA_TABLE.xlsx
--@C:\Users\Samiksha\BIN_dWNUZEuJQS24wJpLIHRMFA==_0_DATA_TABLE.xlsx
--@C:\Users\Samiksha\BIN_jTib5X59TCitUh6p6Zjylw==_0_DATA_TABLE.xlsx
--@C:\Users\Samiksha\COMPANY_DATA_TABLE.xlsx
--@C:\Users\Samiksha\PLACEMENT_DATA_TABLE.xlsx
--@C:\Users\Samiksha\STUDENT_DATA_TABLE.xlsx
@C:\Users\Samiksha\COMPANY_PK.sql
@C:\Users\Samiksha\PLACEMENT_PK.sql
@C:\Users\Samiksha\STUDENT_PK.sql
@C:\Users\Samiksha\COMPANY_CONSTRAINT.sql
@C:\Users\Samiksha\PLACEMENT_CONSTRAINT.sql
@C:\Users\Samiksha\STUDENT_CONSTRAINT.sql
@C:\Users\Samiksha\PLACEMENT_REFCONSTRAINT.sql
@C:\Users\Samiksha\ADMISSION.sql
@C:\Users\Samiksha\BRNCHPRFM.sql
@C:\Users\Samiksha\SEARCH.sql
@C:\Users\Samiksha\SEARCHC.sql
@C:\Users\Samiksha\TOP_COMPANY.sql
@C:\Users\Samiksha\TOP_PERFORMER.sql
