--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "PROJECT"."STUDENT" 
   (	"ROLLNO" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"FATHERNAME" VARCHAR2(50 BYTE), 
	"BRANCH" VARCHAR2(3 BYTE), 
	"YEAR" NUMBER, 
	"ADDRESS" VARCHAR2(150 BYTE), 
	"MOBILENO" NUMBER, 
	"EMAIL" VARCHAR2(75 BYTE), 
	"GENDER" VARCHAR2(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
